// Generated by LiveScript 1.3.1
(function(){
  var mailparser, fs, parser, email;
  mailparser = require('mailparser');
  fs = require('fs');
  parser = new mailparser.MailParser();
  email = fs.readFileSync(process.argv[2], 'utf-8');
  parser.on('end', function(mail){
    var i$, ref$, len$, attachment, fileName, content, results$ = [];
    for (i$ = 0, len$ = (ref$ = mail.attachments).length; i$ < len$; ++i$) {
      attachment = ref$[i$];
      fileName = attachment.fileName, content = attachment.content;
      results$.push(fs.writeFileSync(fileName, content));
    }
    return results$;
  });
  parser.write(email);
  parser.end();
}).call(this);
